name: Android PR Build
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: takuyaohashi/setup-flutter@v1
      with:
        flutter-version: 'latest'
        channel: 'stable'
    - name: Copy Credentials
      run: echo $GOOGLE_SERVICES_JSON > android/app/google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
    - name: Flutter Build
      run: flutter pub get
    - name: Flutter Analyze
      run: flutter analyze .
    - name: Flutter Test
      run: flutter test
    - name: Build APK
      run: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi --debug --verbose
